### ISSUE TITLE
transformers library version should be specified

### ISSUE THREAD

**Issue by oliviersalaun** [maastrichtlawtech/bsard#1]
Hi,

As specified in the documentation, I made the environment from the yml file:
`time conda env create -n bsard -f environment.yml`

However, I run into an error when doing the grid search:
```
Traceback (most recent call last):                                                                                                                                                   
  File "scripts/search_hyperparameters.py", line 11, in <module>
    from retriever import Word2vecRetriever, FasttextRetriever, BERTRetriever
  File "/u/salaunol/Documents/_2021_automne/bsard/scripts/retriever.py", line 16, in <module>
    from transformers import (CamembertModel, CamembertTokenizer,
ImportError: cannot import name 'CamembertModel' from 'transformers' (/u/salaunol/anaconda3/envs/bsard/lib/python3.8/site-packages/transformers/__init__.py)
```

The transformers version was the following:
`transformers              2.1.1              pyhd3eb1b0_0`

I fixed it with `pip install transformers==2.5.0` but it would be preferable to specify the version for each library in `environment.yml`

Edit: issue submitted too fast

**Comment by ant-louis** [comment]
Hi, thanks for pointing that out. The version of each library is now specified in the `requirements.txt` file.
